<a href="https://colab.research.google.com/github/patrick251s/MachineLearning/blob/main/k_sasiady.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import xlrd as xd
from google.colab import files
from google.colab import drive
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score
from sklearn import metrics

drive.mount('/gdrive')
myCsvFile = 'grains.csv'
dir_Path = '/gdrive/My Drive/MojeStudia/Semestr VIII/PiPAN/Analiza danych/'
df = pd.read_csv(dir_Path+myCsvFile)

df_temp = df
x = df_temp.drop(['group', 'compactness', 'area', 'perimeter'], axis=1)
y = df.group.to_numpy()

def Train(x, y, size):
  x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=size, random_state=42)
  return x_train, x_test, y_train, y_test

def Model(x_train, y_train, nn):
  knn = KNeighborsClassifier(n_neighbors=nn) # k = 3
  knn.fit(x_train, y_train)
  y_pred = knn.predict(x_test)
  return y_pred

x_train, x_test, y_train, y_test = Train(x, y, 0.25)
y_pred = Model(x_train, y_train, 3)
accuracy = accuracy_score(y_test, y_pred)*100
print("accuracy = ", accuracy)
mtr = metrics.confusion_matrix(y_test, y_pred)
print(mtr)

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
accuracy =  91.66666666666666
[[11  1  0]
 [ 0 12  1]
 [ 1  0 10]]
